AWSTemplateFormatVersion: "2010-09-09"
Description: Static website S3 bucket with public read access (for demo/testing)
# Description of what this change includes
# Revision 2
# 10/26/2025

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Id: MyPolicy
        Statement:
          - Sid: PublicReadForGetBucketObjects
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${S3Bucket}/*"

Outputs:
  WebsiteURL:
    Description: URL for website hosted on S3 (HTTP, website endpoint)
    Value: !GetAtt S3Bucket.WebsiteURL

  S3BucketSecureURL:
    Description: HTTPS virtual-hosted–style endpoint (not the website endpoint)
    Value: !Join
      - ""
      - - "https://"
        - !GetAtt S3Bucket.DomainName
